# Generated by Django 5.1.3 on 2024-12-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contact_expertise_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
